# Matrix Algebra
---
**Name:** Jonh Alexis Buot <br>
**Date:** December 2023 <br>
**Course:** CS3101N <br>
**Task:** Assignment - Matrix Algebra

---

In [62]:
import numpy as np

# Code Challenges

For the coding challenges, sample executions would be shown, as well as `numpy` executions to compare the results of the two.

**1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.**

In [63]:
def matrix_add(A, B):
# =============================================================================
#   Performs matrix addition on 2 numpy matrices: A and B.
# =============================================================================
    assert len(A.shape), "A must be a matrix (2D numpy array.)"
    assert len(B.shape), "B must be a matrix (2D numpy array.)"
    assert A.shape == B.shape, "Matrices must be of the same shape."

    m = A.shape[0]
    n = A.shape[1]

    sum = np.copy(A).astype("float64")
    
    for i in range(m):
        for j in range(n):
            sum[i][j] += B[i][j]

    return sum

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")
B = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_add(A, B)
np_result = A + B

print("-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- My A + B --", my_result, sep="\n")
print("\n-- Numpy A + B --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[ 20.   7.  36. -18.]
 [ 49.  40.  21. -21.]
 [-12.  46.  19.  32.]
 [ 34. -34.  45.  40.]
 [ 10.  39.   2.  10.]]

-- B --
[[ 14.  -8. -37. -25.]
 [ -4. -31. -22.  34.]
 [ 34. -33. -24.  15.]
 [-29.   0. -39.   4.]
 [  5. -31. -28.  19.]]

-- My A + B --
[[ 34.  -1.  -1. -43.]
 [ 45.   9.  -1.  13.]
 [ 22.  13.  -5.  47.]
 [  5. -34.   6.  44.]
 [ 15.   8. -26.  29.]]

-- Numpy A + B --
[[ 34.  -1.  -1. -43.]
 [ 45.   9.  -1.  13.]
 [ 22.  13.  -5.  47.]
 [  5. -34.   6.  44.]
 [ 15.   8. -26.  29.]]

Are my results equal to numpy? Yes.


**2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.**

In [64]:
def matrix_multiply(A, B):
# =============================================================================
#   Performs matrix multiplication on 2 numpy matrices: A and B.
# =============================================================================
    assert len(A.shape), "A must be a matrix (2D numpy array.)"
    assert len(B.shape), "B must be a matrix (2D numpy array.)"
    # A = m x s, B = s x n
    assert A.shape[1] == B.shape[0], "Columns of Matrix A must equal rows of matrix B."

    m = A.shape[0]
    s = A.shape[1]
    n = B.shape[1]

    product = np.zeros((m, n), dtype="float64")

    for i in range(m):
        for j in range(n):
            product[i][j] = sum(A[i][k] * B[k][j] for k in range(s))

    return product

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")
B = np.random.randint(-50, 50, size=(4, 5)).astype("float64")

my_result = matrix_multiply(A, B)
np_result = np.matmul(A, B)

print("-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- My A * B --", my_result, sep="\n")
print("\n-- Numpy A * B --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[ 11.  16.  44.  -7.]
 [-21. -21. -36.  35.]
 [-17.  23.  -1.  -5.]
 [  4. -23. -50.  31.]
 [-33. -11.   0.  29.]]

-- B --
[[-14. -19.   0.  47.   3.]
 [-34.  28. -19.  -5. -25.]
 [-18. -19.  18.  44.  34.]
 [ 31.  39. -16. -32.  19.]]

-- My A * B --
[[-1707.  -870.   600.  2597.   996.]
 [ 2741.  1860.  -809. -3586.   -97.]
 [ -681.   791.  -375.  -798.  -755.]
 [ 2587.  1439.  -959. -2889.  -524.]
 [ 1735.  1450.  -255. -2424.   727.]]

-- Numpy A * B --
[[-1707.  -870.   600.  2597.   996.]
 [ 2741.  1860.  -809. -3586.   -97.]
 [ -681.   791.  -375.  -798.  -755.]
 [ 2587.  1439.  -959. -2889.  -524.]
 [ 1735.  1450.  -255. -2424.   727.]]

Are my results equal to numpy? Yes.


**3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.**

In [65]:
def matrix_scale(A, k):
# =============================================================================
#   Performs scalar multiplication on a numpy matrix A.
# =============================================================================
    assert len(A.shape), "A must be a matrix (2D numpy array.)"

    m = A.shape[0]
    n = A.shape[1]

    scaled = np.copy(A).astype("float64")

    for i in range(m):
        for j in range(n):
            scaled[i][j] *= k

    return scaled

A = np.random.randint(-50, 50, size=(4, 3)).astype("float64")
B = np.random.randint(-50, 50, size=(4, 3)).astype("float64")
k = np.random.randint(-10, 10)

# k(A + B)
scalar_multiply_sum = matrix_scale(matrix_add(A, B), k)

# kA + kB
scalar_multiply_matrices_then_sum = matrix_add(matrix_scale(A, k), matrix_scale(B, k))

print("-- k --", k, sep="\n")
print("\n-- A --", A, sep="\n")
print("\n-- B --", B, sep="\n")
print("\n-- k(A + B) --", scalar_multiply_sum, sep="\n")
print("\n-- kA + kB --", scalar_multiply_matrices_then_sum, sep="\n")
print("\nAre the results equal?", "Yes." if (scalar_multiply_matrices_then_sum == scalar_multiply_sum).all() else "No.")

-- k --
9

-- A --
[[ 10.  -5.  -8.]
 [-15.  29. -38.]
 [  0.  -2. -38.]
 [-25.   4.  36.]]

-- B --
[[ 49.   7.   4.]
 [ 35. -22.  28.]
 [ 18.  44.  40.]
 [-11. -40.  33.]]

-- k(A + B) --
[[ 531.   18.  -36.]
 [ 180.   63.  -90.]
 [ 162.  378.   18.]
 [-324. -324.  621.]]

-- kA + kB --
[[ 531.   18.  -36.]
 [ 180.   63.  -90.]
 [ 162.  378.   18.]
 [-324. -324.  621.]]

Are the results equal? Yes.


**4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.**

In [66]:
def matrix_diag(A):
# =============================================================================
#   Get the diagonal of a numpy matrix A.
# =============================================================================
    assert len(A.shape), "A must be a matrix (2D numpy array.)"

    n = min(A.shape)
    return np.array([A[i][i] for i in range(n)]).astype("float64")

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_diag(A)
np_result = np.diag(A)

print("-- A --", A, sep="\n")
print("\n-- My diag(A) --", my_result, sep="\n")
print("\n-- Numpy diag(A) --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[  8.  29.   8.  28.]
 [  0. -34.  -5.  17.]
 [  1.  44.   0.  23.]
 [-14. -50.  14.  37.]
 [  4.  -2. -28. -39.]]

-- My diag(A) --
[  8. -34.   0.  37.]

-- Numpy diag(A) --
[  8. -34.   0.  37.]

Are my results equal to numpy? Yes.


**5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.**

In [67]:
def matrix_trace(A):
# =============================================================================
#   Get the trace of a numpy matrix A.
# =============================================================================
    assert len(A.shape), "A must be a matrix (2D numpy array.)"
    
    n = min(A.shape)
    return sum(A[i][i] for i in range(n))

A = np.random.randint(-50, 50, size=(5, 4)).astype("float64")

my_result = matrix_trace(A)
np_result = np.trace(A)

print("-- A --", A, sep="\n")
print("\n-- My tr(A) --", my_result, sep="\n")
print("\n-- Numpy tr(A) --", np_result, sep="\n")
print("\nAre my results equal to numpy?", "Yes." if (my_result == np_result).all() else "No.")

-- A --
[[ 39.  26.  13. -12.]
 [ 29.  25.  19.   9.]
 [-20. -49.  38.  39.]
 [ 21.  -5.  36.  49.]
 [ -3.  -6. -33.  11.]]

-- My tr(A) --
151.0

-- Numpy tr(A) --
151.0

Are my results equal to numpy? Yes.
